/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIAccidentallyMarriedAVampireRouteImport } from './routes/books.i-accidentally-married-a-vampire'
import { Route as AuthorsZoraMonroeRouteImport } from './routes/authors.zora-monroe'
import { Route as AuthorsScarlettValeRouteImport } from './routes/authors.scarlett-vale'
import { Route as AuthorsEverlyQuinnRouteImport } from './routes/authors.everly-quinn'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIAccidentallyMarriedAVampireRoute =
  BooksIAccidentallyMarriedAVampireRouteImport.update({
    id: '/i-accidentally-married-a-vampire',
    path: '/i-accidentally-married-a-vampire',
    getParentRoute: () => BooksRoute,
  } as any)
const AuthorsZoraMonroeRoute = AuthorsZoraMonroeRouteImport.update({
  id: '/zora-monroe',
  path: '/zora-monroe',
  getParentRoute: () => AuthorsRoute,
} as any)
const AuthorsScarlettValeRoute = AuthorsScarlettValeRouteImport.update({
  id: '/scarlett-vale',
  path: '/scarlett-vale',
  getParentRoute: () => AuthorsRoute,
} as any)
const AuthorsEverlyQuinnRoute = AuthorsEverlyQuinnRouteImport.update({
  id: '/everly-quinn',
  path: '/everly-quinn',
  getParentRoute: () => AuthorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/authors/everly-quinn': typeof AuthorsEverlyQuinnRoute
  '/authors/scarlett-vale': typeof AuthorsScarlettValeRoute
  '/authors/zora-monroe': typeof AuthorsZoraMonroeRoute
  '/books/i-accidentally-married-a-vampire': typeof BooksIAccidentallyMarriedAVampireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/authors/everly-quinn': typeof AuthorsEverlyQuinnRoute
  '/authors/scarlett-vale': typeof AuthorsScarlettValeRoute
  '/authors/zora-monroe': typeof AuthorsZoraMonroeRoute
  '/books/i-accidentally-married-a-vampire': typeof BooksIAccidentallyMarriedAVampireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/authors/everly-quinn': typeof AuthorsEverlyQuinnRoute
  '/authors/scarlett-vale': typeof AuthorsScarlettValeRoute
  '/authors/zora-monroe': typeof AuthorsZoraMonroeRoute
  '/books/i-accidentally-married-a-vampire': typeof BooksIAccidentallyMarriedAVampireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authors'
    | '/books'
    | '/contact'
    | '/authors/everly-quinn'
    | '/authors/scarlett-vale'
    | '/authors/zora-monroe'
    | '/books/i-accidentally-married-a-vampire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authors'
    | '/books'
    | '/contact'
    | '/authors/everly-quinn'
    | '/authors/scarlett-vale'
    | '/authors/zora-monroe'
    | '/books/i-accidentally-married-a-vampire'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authors'
    | '/books'
    | '/contact'
    | '/authors/everly-quinn'
    | '/authors/scarlett-vale'
    | '/authors/zora-monroe'
    | '/books/i-accidentally-married-a-vampire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthorsRoute: typeof AuthorsRouteWithChildren
  BooksRoute: typeof BooksRouteWithChildren
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/i-accidentally-married-a-vampire': {
      id: '/books/i-accidentally-married-a-vampire'
      path: '/i-accidentally-married-a-vampire'
      fullPath: '/books/i-accidentally-married-a-vampire'
      preLoaderRoute: typeof BooksIAccidentallyMarriedAVampireRouteImport
      parentRoute: typeof BooksRoute
    }
    '/authors/zora-monroe': {
      id: '/authors/zora-monroe'
      path: '/zora-monroe'
      fullPath: '/authors/zora-monroe'
      preLoaderRoute: typeof AuthorsZoraMonroeRouteImport
      parentRoute: typeof AuthorsRoute
    }
    '/authors/scarlett-vale': {
      id: '/authors/scarlett-vale'
      path: '/scarlett-vale'
      fullPath: '/authors/scarlett-vale'
      preLoaderRoute: typeof AuthorsScarlettValeRouteImport
      parentRoute: typeof AuthorsRoute
    }
    '/authors/everly-quinn': {
      id: '/authors/everly-quinn'
      path: '/everly-quinn'
      fullPath: '/authors/everly-quinn'
      preLoaderRoute: typeof AuthorsEverlyQuinnRouteImport
      parentRoute: typeof AuthorsRoute
    }
  }
}

interface AuthorsRouteChildren {
  AuthorsEverlyQuinnRoute: typeof AuthorsEverlyQuinnRoute
  AuthorsScarlettValeRoute: typeof AuthorsScarlettValeRoute
  AuthorsZoraMonroeRoute: typeof AuthorsZoraMonroeRoute
}

const AuthorsRouteChildren: AuthorsRouteChildren = {
  AuthorsEverlyQuinnRoute: AuthorsEverlyQuinnRoute,
  AuthorsScarlettValeRoute: AuthorsScarlettValeRoute,
  AuthorsZoraMonroeRoute: AuthorsZoraMonroeRoute,
}

const AuthorsRouteWithChildren =
  AuthorsRoute._addFileChildren(AuthorsRouteChildren)

interface BooksRouteChildren {
  BooksIAccidentallyMarriedAVampireRoute: typeof BooksIAccidentallyMarriedAVampireRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksIAccidentallyMarriedAVampireRoute:
    BooksIAccidentallyMarriedAVampireRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthorsRoute: AuthorsRouteWithChildren,
  BooksRoute: BooksRouteWithChildren,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-router' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
