/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthorsAuthorSlugRouteImport } from './routes/authors.$authorSlug'
import { Route as BooksBookSlugRouteImport } from './routes/books.$bookSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorSlugRoute = AuthorsAuthorSlugRouteImport.update({
  id: '/$authorSlug',
  path: '/$authorSlug',
  getParentRoute: () => AuthorsRoute,
} as any)
const BooksBookSlugRoute = BooksBookSlugRouteImport.update({
  id: '/$bookSlug',
  path: '/$bookSlug',
  getParentRoute: () => BooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/authors/$authorSlug': typeof AuthorsAuthorSlugRoute
  '/books/$bookSlug': typeof BooksBookSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/authors/$authorSlug': typeof AuthorsAuthorSlugRoute
  '/books/$bookSlug': typeof BooksBookSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/authors/$authorSlug': typeof AuthorsAuthorSlugRoute
  '/books/$bookSlug': typeof BooksBookSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authors'
    | '/books'
    | '/contact'
    | '/authors/$authorSlug'
    | '/books/$bookSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authors'
    | '/books'
    | '/contact'
    | '/authors/$authorSlug'
    | '/books/$bookSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authors'
    | '/books'
    | '/contact'
    | '/authors/$authorSlug'
    | '/books/$bookSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthorsRoute: typeof AuthorsRouteWithChildren
  BooksRoute: typeof BooksRouteWithChildren
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorSlug': {
      id: '/authors/$authorSlug'
      path: '/$authorSlug'
      fullPath: '/authors/$authorSlug'
      preLoaderRoute: typeof AuthorsAuthorSlugRouteImport
      parentRoute: typeof AuthorsRoute
    }
    '/books/$bookSlug': {
      id: '/books/$bookSlug'
      path: '/$bookSlug'
      fullPath: '/books/$bookSlug'
      preLoaderRoute: typeof BooksBookSlugRouteImport
      parentRoute: typeof BooksRoute
    }
  }
}

interface AuthorsRouteChildren {
  AuthorsAuthorSlugRoute: typeof AuthorsAuthorSlugRoute
}

const AuthorsRouteChildren: AuthorsRouteChildren = {
  AuthorsAuthorSlugRoute: AuthorsAuthorSlugRoute,
}

const AuthorsRouteWithChildren =
  AuthorsRoute._addFileChildren(AuthorsRouteChildren)

interface BooksRouteChildren {
  BooksBookSlugRoute: typeof BooksBookSlugRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookSlugRoute: BooksBookSlugRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthorsRoute: AuthorsRouteWithChildren,
  BooksRoute: BooksRouteWithChildren,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
